[package]
name = "register"
type = "bin"
authors = ["zk-experiments"]
compiler_version = ">=1.0.0"

[dependencies]
identity_cache = { path = "../../lib/identity_cache" }
eid_steps = { git = "https://github.com/zk-experiments/eid-circuits", tag = "v0.8.0", directory = "noir/lib/steps" }
